// Code generated by the Encore 1.56.0 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly agent: agent.ServiceClient
    public readonly approvals: approvals.ServiceClient
    public readonly audit: audit.ServiceClient
    public readonly cases: cases.ServiceClient
    public readonly drafts: drafts.ServiceClient
    public readonly evidence: evidence.ServiceClient
    public readonly ingest: ingest.ServiceClient
    public readonly policy: policy.ServiceClient
    public readonly simulation: simulation.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.agent = new agent.ServiceClient(base)
        this.approvals = new approvals.ServiceClient(base)
        this.audit = new audit.ServiceClient(base)
        this.cases = new cases.ServiceClient(base)
        this.drafts = new drafts.ServiceClient(base)
        this.evidence = new evidence.ServiceClient(base)
        this.ingest = new ingest.ServiceClient(base)
        this.policy = new policy.ServiceClient(base)
        this.simulation = new simulation.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getAgentRun as api_agent_get_run_getAgentRun } from "~backend/agent/get_run";
import { listAgentSteps as api_agent_list_steps_listAgentSteps } from "~backend/agent/list_steps";
import { runAgent as api_agent_run_runAgent } from "~backend/agent/run";

export namespace agent {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getAgentRun = this.getAgentRun.bind(this)
            this.listAgentSteps = this.listAgentSteps.bind(this)
            this.runAgent = this.runAgent.bind(this)
        }

        /**
         * Retrieves an agent run with all trace steps.
         */
        public async getAgentRun(params: { id: string }): Promise<ResponseType<typeof api_agent_get_run_getAgentRun>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/agent/runs/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agent_get_run_getAgentRun>
        }

        /**
         * Lists all agent trace steps for a given case.
         */
        public async listAgentSteps(params: RequestType<typeof api_agent_list_steps_listAgentSteps>): Promise<ResponseType<typeof api_agent_list_steps_listAgentSteps>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "case_id": params["case_id"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/agent/steps`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agent_list_steps_listAgentSteps>
        }

        /**
         * Executes the autonomous evidence-gathering agent for a dispute case.
         */
        public async runAgent(params: RequestType<typeof api_agent_run_runAgent>): Promise<ResponseType<typeof api_agent_run_runAgent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/agent/run`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agent_run_runAgent>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createApproval as api_approvals_create_createApproval } from "~backend/approvals/create";
import { listApprovals as api_approvals_list_listApprovals } from "~backend/approvals/list";

export namespace approvals {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createApproval = this.createApproval.bind(this)
            this.listApprovals = this.listApprovals.bind(this)
        }

        /**
         * Records an approval decision and updates the case status accordingly.
         */
        public async createApproval(params: RequestType<typeof api_approvals_create_createApproval>): Promise<ResponseType<typeof api_approvals_create_createApproval>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/approvals`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_approvals_create_createApproval>
        }

        /**
         * Lists all approval records for a given case.
         */
        public async listApprovals(params: RequestType<typeof api_approvals_list_listApprovals>): Promise<ResponseType<typeof api_approvals_list_listApprovals>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "case_id": params["case_id"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/approvals`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_approvals_list_listApprovals>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { listAudit as api_audit_list_listAudit } from "~backend/audit/list";
import { log as api_audit_log_log } from "~backend/audit/log";

export namespace audit {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.listAudit = this.listAudit.bind(this)
            this.log = this.log.bind(this)
        }

        /**
         * Retrieves the full audit trail for a given case.
         */
        public async listAudit(params: RequestType<typeof api_audit_list_listAudit>): Promise<ResponseType<typeof api_audit_list_listAudit>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "case_id": params["case_id"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/audit`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_audit_list_listAudit>
        }

        /**
         * Creates an immutable audit log entry.
         */
        public async log(params: RequestType<typeof api_audit_log_log>): Promise<ResponseType<typeof api_audit_log_log>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/audit`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_audit_log_log>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { get as api_cases_get_get } from "~backend/cases/get";
import { list as api_cases_list_list } from "~backend/cases/list";
import { stats as api_cases_stats_stats } from "~backend/cases/stats";
import { update as api_cases_update_update } from "~backend/cases/update";

export namespace cases {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.stats = this.stats.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Retrieves a single dispute case by ID.
         */
        public async get(params: { id: string }): Promise<ResponseType<typeof api_cases_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cases/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cases_get_get>
        }

        /**
         * Lists all dispute cases with optional filters.
         */
        public async list(params: RequestType<typeof api_cases_list_list>): Promise<ResponseType<typeof api_cases_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                recommendation:  params.recommendation,
                "scenario_type": params["scenario_type"],
                status:          params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cases`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cases_list_list>
        }

        /**
         * Returns aggregate statistics for the cases dashboard.
         */
        public async stats(): Promise<ResponseType<typeof api_cases_stats_stats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cases/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cases_stats_stats>
        }

        /**
         * Updates a dispute case's status, recommendation, or other mutable fields.
         */
        public async update(params: RequestType<typeof api_cases_update_update>): Promise<ResponseType<typeof api_cases_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "approval_state":              params["approval_state"],
                "confidence_band":             params["confidence_band"],
                "evidence_completeness_score": params["evidence_completeness_score"],
                recommendation:                params.recommendation,
                status:                        params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cases/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cases_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createDraft as api_drafts_create_createDraft } from "~backend/drafts/create";
import { listDrafts as api_drafts_list_listDrafts } from "~backend/drafts/list";
import { updateDraft as api_drafts_update_updateDraft } from "~backend/drafts/update";

export namespace drafts {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createDraft = this.createDraft.bind(this)
            this.listDrafts = this.listDrafts.bind(this)
            this.updateDraft = this.updateDraft.bind(this)
        }

        /**
         * Generates a bank-facing dispute response draft for a case.
         */
        public async createDraft(params: RequestType<typeof api_drafts_create_createDraft>): Promise<ResponseType<typeof api_drafts_create_createDraft>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/drafts`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_drafts_create_createDraft>
        }

        /**
         * Lists all draft versions for a given case.
         */
        public async listDrafts(params: RequestType<typeof api_drafts_list_listDrafts>): Promise<ResponseType<typeof api_drafts_list_listDrafts>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "case_id": params["case_id"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/drafts`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_drafts_list_listDrafts>
        }

        /**
         * Updates the text content of a draft response.
         */
        public async updateDraft(params: RequestType<typeof api_drafts_update_updateDraft>): Promise<ResponseType<typeof api_drafts_update_updateDraft>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "response_text": params["response_text"],
                "summary_text":  params["summary_text"],
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/drafts/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_drafts_update_updateDraft>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createEvidence as api_evidence_create_createEvidence } from "~backend/evidence/create";
import { listEvidence as api_evidence_list_listEvidence } from "~backend/evidence/list";

export namespace evidence {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createEvidence = this.createEvidence.bind(this)
            this.listEvidence = this.listEvidence.bind(this)
        }

        /**
         * Creates a new evidence item for a case.
         */
        public async createEvidence(params: RequestType<typeof api_evidence_create_createEvidence>): Promise<ResponseType<typeof api_evidence_create_createEvidence>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/evidence`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_evidence_create_createEvidence>
        }

        /**
         * Lists all evidence items for a given case.
         */
        public async listEvidence(params: RequestType<typeof api_evidence_list_listEvidence>): Promise<ResponseType<typeof api_evidence_list_listEvidence>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "case_id": params["case_id"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/evidence`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_evidence_list_listEvidence>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { ingestEvent as api_ingest_ingest_ingestEvent } from "~backend/ingest/ingest";

export namespace ingest {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.ingestEvent = this.ingestEvent.bind(this)
        }

        /**
         * Ingests an external event idempotently, deduplicating by external_event_id.
         */
        public async ingestEvent(params: RequestType<typeof api_ingest_ingest_ingestEvent>): Promise<ResponseType<typeof api_ingest_ingest_ingestEvent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ingest/event`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ingest_ingest_ingestEvent>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { evaluate as api_policy_evaluate_evaluate } from "~backend/policy/evaluate";
import { getDecisions as api_policy_get_getDecisions } from "~backend/policy/get";

export namespace policy {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.evaluate = this.evaluate.bind(this)
            this.getDecisions = this.getDecisions.bind(this)
        }

        /**
         * Evaluates a deterministic rule-based policy for a dispute case.
         */
        public async evaluate(params: RequestType<typeof api_policy_evaluate_evaluate>): Promise<ResponseType<typeof api_policy_evaluate_evaluate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/policy/evaluate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_policy_evaluate_evaluate>
        }

        /**
         * Retrieves all policy decisions for a given case.
         */
        public async getDecisions(params: RequestType<typeof api_policy_get_getDecisions>): Promise<ResponseType<typeof api_policy_get_getDecisions>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "case_id": params["case_id"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/policy/decisions`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_policy_get_getDecisions>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { reset as api_simulation_reset_reset } from "~backend/simulation/reset";
import { seed as api_simulation_seed_seed } from "~backend/simulation/seed";
import { simulate as api_simulation_simulate_simulate } from "~backend/simulation/simulate";

export namespace simulation {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.reset = this.reset.bind(this)
            this.seed = this.seed.bind(this)
            this.simulate = this.simulate.bind(this)
        }

        /**
         * Truncates all tables and reseeds all demo scenarios.
         */
        public async reset(): Promise<ResponseType<typeof api_simulation_reset_reset>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/simulation/reset`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_simulation_reset_reset>
        }

        /**
         * Seeds all 4 demo scenarios for the dispute defense engine.
         */
        public async seed(): Promise<ResponseType<typeof api_simulation_seed_seed>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/simulation/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_simulation_seed_seed>
        }

        /**
         * Runs a full end-to-end simulation for a given scenario type.
         */
        public async simulate(params: RequestType<typeof api_simulation_simulate_simulate>): Promise<ResponseType<typeof api_simulation_simulate_simulate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/simulation/simulate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_simulation_simulate_simulate>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.56.0)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
