// Code generated by the Encore v1.53.6 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-dispute-defense-hq-7dki.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the dispute-defense-engine-5ayi Encore application.
 */
export default class Client {
    public readonly agent: agent.ServiceClient
    public readonly approvals: approvals.ServiceClient
    public readonly audit: audit.ServiceClient
    public readonly cases: cases.ServiceClient
    public readonly drafts: drafts.ServiceClient
    public readonly evidence: evidence.ServiceClient
    public readonly frontend: frontend.ServiceClient
    public readonly ingest: ingest.ServiceClient
    public readonly policy: policy.ServiceClient
    public readonly simulation: simulation.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.agent = new agent.ServiceClient(base)
        this.approvals = new approvals.ServiceClient(base)
        this.audit = new audit.ServiceClient(base)
        this.cases = new cases.ServiceClient(base)
        this.drafts = new drafts.ServiceClient(base)
        this.evidence = new evidence.ServiceClient(base)
        this.frontend = new frontend.ServiceClient(base)
        this.ingest = new ingest.ServiceClient(base)
        this.policy = new policy.ServiceClient(base)
        this.simulation = new simulation.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

export namespace agent {
    export interface AgentRun {
        id: string
        "case_id": string
        status: AgentRunStatus
        "step_count": number
        "started_at": string
        "ended_at": string | null
        "final_summary": string | null
    }

    export type AgentRunStatus = "running" | "completed" | "failed"

    export interface AgentTraceStep {
        id: string
        "agent_run_id": string
        "case_id": string
        "step_number": number
        "action_type": string
        "tool_name": string | null
        "input_json": { [key: string]: any }
        "output_json": { [key: string]: any }
        "observation_text": string
        status: TraceStepStatus
        "created_at": string
    }

    export interface GetRunResponse {
        run: AgentRun
        steps: AgentTraceStep[]
    }

    export interface ListStepsParams {
        "case_id": string
    }

    export interface ListStepsResponse {
        steps: AgentTraceStep[]
    }

    export interface RunAgentParams {
        "case_id": string
        "scenario_type": string
    }

    export interface RunAgentResponse {
        run: AgentRun
        steps: AgentTraceStep[]
    }

    export type TraceStepStatus = "success" | "warning" | "error" | "pending"

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getAgentRun = this.getAgentRun.bind(this)
            this.listAgentSteps = this.listAgentSteps.bind(this)
            this.runAgent = this.runAgent.bind(this)
        }

        /**
         * Retrieves an agent run with all trace steps.
         */
        public async getAgentRun(id: string): Promise<GetRunResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/agent/runs/${encodeURIComponent(id)}`)
            return await resp.json() as GetRunResponse
        }

        /**
         * Lists all agent trace steps for a given case.
         */
        public async listAgentSteps(params: ListStepsParams): Promise<ListStepsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "case_id": params["case_id"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/agent/steps`, undefined, {query})
            return await resp.json() as ListStepsResponse
        }

        /**
         * Executes the autonomous evidence-gathering agent for a dispute case.
         */
        public async runAgent(params: RunAgentParams): Promise<RunAgentResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/agent/run`, JSON.stringify(params))
            return await resp.json() as RunAgentResponse
        }
    }
}

export namespace approvals {
    export interface Approval {
        id: string
        "case_id": string
        "draft_id": string | null
        "actor_role": string
        "actor_name": string
        decision: ApprovalDecision
        notes: string | null
        "created_at": string
    }

    export type ApprovalDecision = "Approved" | "Rejected" | "Sent Back"

    export interface CreateApprovalParams {
        "case_id": string
        "draft_id"?: string
        "actor_role": string
        "actor_name": string
        decision: ApprovalDecision
        notes?: string
    }

    export interface ListApprovalsParams {
        "case_id": string
    }

    export interface ListApprovalsResponse {
        approvals: Approval[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createApproval = this.createApproval.bind(this)
            this.listApprovals = this.listApprovals.bind(this)
        }

        /**
         * Records an approval decision and updates the case status accordingly.
         */
        public async createApproval(params: CreateApprovalParams): Promise<Approval> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/approvals`, JSON.stringify(params))
            return await resp.json() as Approval
        }

        /**
         * Lists all approval records for a given case.
         */
        public async listApprovals(params: ListApprovalsParams): Promise<ListApprovalsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "case_id": params["case_id"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/approvals`, undefined, {query})
            return await resp.json() as ListApprovalsResponse
        }
    }
}

export namespace audit {
    export type ActorType = "system" | "agent" | "operator" | "approver"

    export interface AuditLog {
        id: string
        "case_id": string
        "actor_type": ActorType
        "actor_name": string
        "action_type": string
        "details_json": { [key: string]: any }
        "created_at": string
    }

    export interface CreateAuditLogParams {
        "case_id": string
        "actor_type": ActorType
        "actor_name": string
        "action_type": string
        "details_json": { [key: string]: any }
    }

    export interface ListAuditParams {
        "case_id": string
    }

    export interface ListAuditResponse {
        logs: AuditLog[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.listAudit = this.listAudit.bind(this)
            this.log = this.log.bind(this)
        }

        /**
         * Retrieves the full audit trail for a given case.
         */
        public async listAudit(params: ListAuditParams): Promise<ListAuditResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "case_id": params["case_id"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/audit`, undefined, {query})
            return await resp.json() as ListAuditResponse
        }

        /**
         * Creates an immutable audit log entry.
         */
        public async log(params: CreateAuditLogParams): Promise<AuditLog> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/audit`, JSON.stringify(params))
            return await resp.json() as AuditLog
        }
    }
}

export namespace cases {
    export type ApprovalState = "Not Needed" | "Pending" | "Approved" | "Rejected" | "Sent Back"

    export interface Case {
        id: string
        "dispute_id": string
        "payment_id": string | null
        "merchant_name": string
        amount: number
        currency: string
        "reason_code": string | null
        "dispute_reason": string
        "respond_by": string | null
        status: CaseStatus
        "external_status": string | null
        phase: string | null
        network: string | null
        "amount_deducted": number | null
        recommendation: Recommendation | null
        "confidence_band": ConfidenceBand | null
        "evidence_completeness_score": number
        "approval_state": ApprovalState
        "scenario_type": ScenarioType
        "created_at": string
        "updated_at": string
    }

    export interface CaseStats {
        total: number
        "ready_for_review": number
        "approval_pending": number
        submitted: number
        "auto_complete_rate": number
        "defended_value": number
    }

    export type CaseStatus = "New" | "Hunting Evidence" | "Ready for Review" | "Approval Pending" | "Ready to Submit" | "Submitted" | "Closed"

    export type ConfidenceBand = "High" | "Medium" | "Low"

    export interface ListCasesParams {
        status?: string
        recommendation?: string
        "scenario_type"?: string
    }

    export interface ListCasesResponse {
        cases: Case[]
    }

    export type Recommendation = "Contest" | "Accept" | "Escalate"

    export type ScenarioType = "slam_dunk_contest" | "vernacular_evidence_contest" | "rto_accept" | "weak_evidence_escalate"

    export interface UpdateCaseParams {
        status?: CaseStatus
        recommendation?: Recommendation
        "confidence_band"?: ConfidenceBand
        "evidence_completeness_score"?: number
        "approval_state"?: ApprovalState
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.stats = this.stats.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Retrieves a single dispute case by ID.
         */
        public async get(id: string): Promise<Case> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/cases/${encodeURIComponent(id)}`)
            return await resp.json() as Case
        }

        /**
         * Lists all dispute cases with optional filters.
         */
        public async list(params: ListCasesParams): Promise<ListCasesResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                recommendation:  params.recommendation,
                "scenario_type": params["scenario_type"],
                status:          params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/cases`, undefined, {query})
            return await resp.json() as ListCasesResponse
        }

        /**
         * Returns aggregate statistics for the cases dashboard.
         */
        public async stats(): Promise<CaseStats> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/cases/stats`)
            return await resp.json() as CaseStats
        }

        /**
         * Updates a dispute case's status, recommendation, or other mutable fields.
         */
        public async update(id: string, params: UpdateCaseParams): Promise<Case> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/cases/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as Case
        }
    }
}

export namespace drafts {
    export interface CreateDraftParams {
        "case_id": string
    }

    export interface Draft {
        id: string
        "case_id": string
        version: number
        "summary_text": string
        "response_text": string
        "attachments_json": string[]
        "created_at": string
        "updated_at": string
    }

    export interface ListDraftsParams {
        "case_id": string
    }

    export interface ListDraftsResponse {
        drafts: Draft[]
    }

    export interface UpdateDraftParams {
        "summary_text"?: string
        "response_text"?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createDraft = this.createDraft.bind(this)
            this.listDrafts = this.listDrafts.bind(this)
            this.updateDraft = this.updateDraft.bind(this)
        }

        /**
         * Generates a bank-facing dispute response draft for a case.
         */
        public async createDraft(params: CreateDraftParams): Promise<Draft> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/drafts`, JSON.stringify(params))
            return await resp.json() as Draft
        }

        /**
         * Lists all draft versions for a given case.
         */
        public async listDrafts(params: ListDraftsParams): Promise<ListDraftsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "case_id": params["case_id"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/drafts`, undefined, {query})
            return await resp.json() as ListDraftsResponse
        }

        /**
         * Updates the text content of a draft response.
         */
        public async updateDraft(id: string, params: UpdateDraftParams): Promise<Draft> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/drafts/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as Draft
        }
    }
}

export namespace evidence {
    export interface CreateEvidenceItemParams {
        "case_id": string
        "evidence_type": EvidenceType
        "source_name": string
        title: string
        "summary_text": string
        "raw_content_json": { [key: string]: any }
        "preview_text": string
        "file_url"?: string
        status: EvidenceStatus
        confidence: number
    }

    export interface EvidenceItem {
        id: string
        "case_id": string
        "evidence_type": EvidenceType
        "source_name": string
        title: string
        "summary_text": string
        "raw_content_json": { [key: string]: any }
        "preview_text": string
        "file_url": string | null
        status: EvidenceStatus
        confidence: number
        "collected_at": string
    }

    export type EvidenceStatus = "found" | "missing" | "partial"

    export type EvidenceType = "payment_record" | "order_details" | "awb_tracking" | "logistics_status" | "proof_of_delivery" | "invoice" | "customer_communication" | "merchant_policy" | "document_ocr"

    export interface ListEvidenceParams {
        "case_id": string
    }

    export interface ListEvidenceResponse {
        items: EvidenceItem[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createEvidence = this.createEvidence.bind(this)
            this.listEvidence = this.listEvidence.bind(this)
        }

        /**
         * Creates a new evidence item for a case.
         */
        public async createEvidence(params: CreateEvidenceItemParams): Promise<EvidenceItem> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/evidence`, JSON.stringify(params))
            return await resp.json() as EvidenceItem
        }

        /**
         * Lists all evidence items for a given case.
         */
        public async listEvidence(params: ListEvidenceParams): Promise<ListEvidenceResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "case_id": params["case_id"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/evidence`, undefined, {query})
            return await resp.json() as ListEvidenceResponse
        }
    }
}

export namespace frontend {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.assets = this.assets.bind(this)
        }

        public async assets(path: string[]): Promise<void> {
            await this.baseClient.callTypedAPI("HEAD", `/frontend/${path.map(encodeURIComponent).join("/")}`)
        }
    }
}

export namespace ingest {
    export interface EventLog {
        id: string
        "external_event_id": string
        "event_type": string
        "processed_at": string
        "payload_json": any
    }

    export interface IngestEventParams {
        "external_event_id": string
        "event_type": string
        payload: {
            dispute: RazorpayDisputePayload
        }
    }

    export interface IngestEventResponse {
        "case_id": string
        "is_duplicate_event": boolean
    }

    export interface ListEventsResponse {
        events: EventLog[]
    }

    export interface RazorpayDisputePayload {
        id: string
        "payment_id": string
        amount: number
        currency: string
        "amount_deducted": number
        "reason_code": string
        "respond_by": number
        status: string
        phase: string
        "created_at": number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.ingestEvent = this.ingestEvent.bind(this)
            this.list = this.list.bind(this)
        }

        /**
         * Ingests a Razorpay dispute event, updating the case lifecycle idempotently.
         */
        public async ingestEvent(params: IngestEventParams): Promise<IngestEventResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/ingest/event`, JSON.stringify(params))
            return await resp.json() as IngestEventResponse
        }

        /**
         * Returns the most recent 50 webhook events for the Live Console.
         */
        public async list(): Promise<ListEventsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/ingest/events`)
            return await resp.json() as ListEventsResponse
        }
    }
}

export namespace policy {
    export interface GetDecisionsParams {
        "case_id": string
    }

    export interface GetDecisionsResponse {
        decisions: PolicyDecision[]
    }

    export interface PolicyDecision {
        id: string
        "case_id": string
        "playbook_name": string
        "recommended_action": "Contest" | "Accept" | "Escalate"
        "confidence_band": "High" | "Medium" | "Low"
        "rationale_json": string[]
        "missing_items_json": string[]
        "approval_required": boolean
        "created_at": string
    }

    export interface PolicyInput {
        "case_id": string
        "reason_code": string | null
        "scenario_type": string
        "logistics_status": string
        "pod_present": boolean
        "invoice_present": boolean
        "customer_communication_state": string
        "evidence_completeness_score": number
        "missing_evidence_types": string[]
        network: string | null
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.evaluate = this.evaluate.bind(this)
            this.getDecisions = this.getDecisions.bind(this)
        }

        /**
         * Evaluates a deterministic rule-based policy using specialized Defense Playbooks.
         */
        public async evaluate(params: PolicyInput): Promise<PolicyDecision> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/policy/evaluate`, JSON.stringify(params))
            return await resp.json() as PolicyDecision
        }

        /**
         * Retrieves all policy decisions for a given case.
         */
        public async getDecisions(params: GetDecisionsParams): Promise<GetDecisionsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "case_id": params["case_id"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/policy/decisions`, undefined, {query})
            return await resp.json() as GetDecisionsResponse
        }
    }
}

export namespace simulation {
    export interface ResetResponse {
        success: boolean
    }

    export interface RunSimParams {
        "scenario_index": number
    }

    export interface RunSimResponse {
        "case_id": string
    }

    export type ScenarioType = "slam_dunk_contest" | "vernacular_evidence_contest" | "rto_accept" | "weak_evidence_escalate"

    export interface SeedResponse {
        "cases_created": number
    }

    export interface SimulateParams {
        "scenario_type": ScenarioType
    }

    export interface SimulateResponse {
        "case_id": string
        case: cases.Case
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.reset = this.reset.bind(this)
            this.runSim = this.runSim.bind(this)
            this.seed = this.seed.bind(this)
            this.simulate = this.simulate.bind(this)
        }

        /**
         * Clears all generated demo data so the environment is empty again.
         */
        public async reset(): Promise<ResetResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/simulation/reset`)
            return await resp.json() as ResetResponse
        }

        /**
         * Runs a specific simulation scenario.
         */
        public async runSim(params: RunSimParams): Promise<RunSimResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/simulation/run`, JSON.stringify(params))
            return await resp.json() as RunSimResponse
        }

        /**
         * Seeds all 4 demo scenarios for the dispute defense engine.
         */
        public async seed(): Promise<SeedResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/simulation/seed`)
            return await resp.json() as SeedResponse
        }

        /**
         * Runs a full end-to-end simulation for a given scenario type.
         */
        public async simulate(params: SimulateParams): Promise<SimulateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/simulation/simulate`, JSON.stringify(params))
            return await resp.json() as SimulateResponse
        }
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "dispute-defense-engine-5ayi-Generated-TS-Client (Encore/v1.53.6)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
