import type { CreateEvidenceItemParams } from "../evidence/types";

export function getSlamDunkEvidence(caseId: string): CreateEvidenceItemParams[] {
  return [
    {
      case_id: caseId,
      evidence_type: "payment_record",
      source_name: "Razorpay",
      title: "Payment pay_abc123 - Captured",
      summary_text: "UPI payment of Rs 2,499 captured on 2026-03-25. VPA: priya.sharma@okicici.",
      raw_content_json: { payment_id: "pay_abc123", amount: 2499, status: "captured", method: "upi" },
      preview_text: "pay_abc123 | Rs 2,499 | captured | UPI",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "order_details",
      source_name: "Shopify",
      title: "Order ORD-4521 - Shipped",
      summary_text: "Order ORD-4521 for Priya Sharma. Urban Cart Premium T-Shirt. AWB: SHP789012 via Shiprocket.",
      raw_content_json: { order_id: "ORD-4521", customer: "Priya Sharma", awb: "SHP789012" },
      preview_text: "ORD-4521 | Priya Sharma | AWB: SHP789012",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "awb_tracking",
      source_name: "Shiprocket",
      title: "AWB SHP789012 - Tracking",
      summary_text: "Shipment tracked: Picked up -> In Transit Delhi Hub -> Delivered on 2026-03-28.",
      raw_content_json: { awb: "SHP789012", events: 3, delivered_at: "2026-03-28T14:30:00Z" },
      preview_text: "SHP789012 | 3 tracking events | Delivered 2026-03-28",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "logistics_status",
      source_name: "Shiprocket",
      title: "Logistics Status - Delivered",
      summary_text: "Final logistics status: Delivered on 2026-03-28T14:30Z to 42, Sector 14, Gurugram.",
      raw_content_json: { status: "Delivered", delivered_at: "2026-03-28T14:30:00Z", location: "Gurugram" },
      preview_text: "Delivered | 2026-03-28T14:30Z | Gurugram",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "proof_of_delivery",
      source_name: "Shiprocket",
      title: "Proof of Delivery - Signed",
      summary_text: "POD available. Recipient signature: P. Sharma. Delivered to registered address.",
      raw_content_json: { pod_available: true, signature: "P. Sharma", address_match: true },
      preview_text: "POD: P. Sharma | Address confirmed",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "invoice",
      source_name: "Merchant ERP",
      title: "Tax Invoice INV-4521",
      summary_text: "GST-compliant tax invoice INV-4521 for Rs 2,499. HSN 61091000. GSTIN: 06AABCU9603R1ZP.",
      raw_content_json: { invoice_id: "INV-4521", amount: 2499, gst: 380.36 },
      preview_text: "INV-4521 | Rs 2,499 | GST: Rs 380.36",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "customer_communication",
      source_name: "Support Desk",
      title: "Support Ticket TKT-98234 - Hindi Complaint",
      summary_text: "Customer complaint (Hindi): 'mujhe order nahi mila'. Translation: 'I did not receive my order.' Contradicted by Shiprocket POD.",
      raw_content_json: { ticket_id: "TKT-98234", original: "mujhe order nahi mila", translated: "I did not receive my order", language: "hi" },
      preview_text: "TKT-98234 | 'mujhe order nahi mila' -> 'I did not receive my order'",
      status: "found",
      confidence: 0.98,
    },
    {
      case_id: caseId,
      evidence_type: "merchant_policy",
      source_name: "Merchant Policy DB",
      title: "Urban Cart Dispute Policy",
      summary_text: "Contest all INR disputes with POD. 7-day return window. POD mandatory for all claims.",
      raw_content_json: { policy: "Contest all INR disputes with POD", return_window_days: 7 },
      preview_text: "Contest policy | 7-day return window | POD mandatory",
      status: "found",
      confidence: 1.0,
    },
  ];
}

export function getVernacularEvidence(caseId: string): CreateEvidenceItemParams[] {
  return [
    {
      case_id: caseId,
      evidence_type: "payment_record",
      source_name: "Razorpay",
      title: "Payment pay_def456 - Captured",
      summary_text: "NetBanking payment of Rs 5,899 captured on 2026-03-20. Bank: HDFC.",
      raw_content_json: { payment_id: "pay_def456", amount: 5899, status: "captured", method: "netbanking" },
      preview_text: "pay_def456 | Rs 5,899 | captured | NetBanking",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "order_details",
      source_name: "Shopify",
      title: "Order ORD-7832 - Shipped",
      summary_text: "Order ORD-7832 for Meenakshi Iyer. Kanjivaram Silk Saree. AWB: SHP345678 via Delhivery.",
      raw_content_json: { order_id: "ORD-7832", customer: "Meenakshi Iyer", awb: "SHP345678" },
      preview_text: "ORD-7832 | Meenakshi Iyer | AWB: SHP345678",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "awb_tracking",
      source_name: "Delhivery",
      title: "AWB SHP345678 - Tracking",
      summary_text: "Delivered on 2026-03-24 via Delhivery. Signature: M. Iyer.",
      raw_content_json: { awb: "SHP345678", delivered_at: "2026-03-24T11:00:00Z" },
      preview_text: "SHP345678 | Delivered 2026-03-24",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "logistics_status",
      source_name: "Delhivery",
      title: "Logistics Status - Delivered",
      summary_text: "Final logistics status: Delivered on 2026-03-24T11:00Z.",
      raw_content_json: { status: "Delivered", delivered_at: "2026-03-24T11:00:00Z" },
      preview_text: "Delivered | 2026-03-24T11:00Z",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "proof_of_delivery",
      source_name: "Delhivery",
      title: "Proof of Delivery - Signed",
      summary_text: "POD available. Signature: M. Iyer.",
      raw_content_json: { pod_available: true, signature: "M. Iyer" },
      preview_text: "POD: M. Iyer | Signed",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "invoice",
      source_name: "Merchant ERP",
      title: "Tax Invoice - MISSING",
      summary_text: "Formal tax invoice not found in ERP. Possible manual billing. Evidence marked partial.",
      raw_content_json: { error: "Invoice not found in ERP" },
      preview_text: "Invoice NOT FOUND",
      status: "missing",
      confidence: 0.0,
    },
    {
      case_id: caseId,
      evidence_type: "customer_communication",
      source_name: "WhatsApp OCR",
      title: "WhatsApp Screenshot - Delivery Acknowledgement",
      summary_text: "OCR of WhatsApp screenshot. Customer message: 'haan, order mil gaya.' Translation: 'Yes, the order arrived.' Confidence: 94%.",
      raw_content_json: { ocr_text: "haan, order mil gaya. bahut sundar saree hai!", translated: "Yes, the order arrived. Very beautiful saree!", confidence: 0.94 },
      preview_text: "'haan, order mil gaya' -> 'Yes, the order arrived'",
      status: "found",
      confidence: 0.94,
    },
    {
      case_id: caseId,
      evidence_type: "merchant_policy",
      source_name: "Merchant Policy DB",
      title: "House of Sarees Dispute Policy",
      summary_text: "Contest with delivery proof and customer acknowledgement. 3-day return window.",
      raw_content_json: { policy: "Contest with delivery proof and customer acknowledgement", return_window_days: 3 },
      preview_text: "Contest policy | 3-day return window",
      status: "found",
      confidence: 1.0,
    },
  ];
}

export function getRtoEvidence(caseId: string): CreateEvidenceItemParams[] {
  return [
    {
      case_id: caseId,
      evidence_type: "payment_record",
      source_name: "Razorpay",
      title: "Payment pay_ghi789 - Captured",
      summary_text: "Visa card payment of Rs 14,999 captured on 2026-03-10.",
      raw_content_json: { payment_id: "pay_ghi789", amount: 14999, status: "captured", method: "card" },
      preview_text: "pay_ghi789 | Rs 14,999 | captured | Visa",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "order_details",
      source_name: "Shopify",
      title: "Order ORD-2291 - Shipped",
      summary_text: "Order ORD-2291. Smartphone ProMax X15. AWB: DHL909876.",
      raw_content_json: { order_id: "ORD-2291", awb: "DHL909876" },
      preview_text: "ORD-2291 | Rohit Verma | AWB: DHL909876",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "awb_tracking",
      source_name: "DHL",
      title: "AWB DHL909876 - RTO",
      summary_text: "Shipment tracking: Picked up -> Out for Delivery -> Delivery Failed -> RTO Initiated.",
      raw_content_json: { awb: "DHL909876", events: 4, rto_at: "2026-03-14T08:00:00Z" },
      preview_text: "DHL909876 | 4 events | RTO 2026-03-14",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "logistics_status",
      source_name: "DHL",
      title: "Logistics Status - RTO",
      summary_text: "Final logistics status: RTO (Return to Origin). Reason: Customer refused delivery on 2026-03-13.",
      raw_content_json: { status: "RTO", rto_reason: "Customer refused delivery", rto_initiated_at: "2026-03-14T08:00:00Z" },
      preview_text: "RTO | Customer refused | 2026-03-14",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "proof_of_delivery",
      source_name: "DHL",
      title: "Proof of Delivery - NOT AVAILABLE",
      summary_text: "No POD available. Delivery failed - customer refused at door.",
      raw_content_json: { pod_available: false, reason: "Customer refused delivery" },
      preview_text: "POD: NOT AVAILABLE | Refused delivery",
      status: "missing",
      confidence: 0.0,
    },
    {
      case_id: caseId,
      evidence_type: "invoice",
      source_name: "Merchant ERP",
      title: "Tax Invoice INV-2291",
      summary_text: "Invoice INV-2291 for Rs 14,999.",
      raw_content_json: { invoice_id: "INV-2291", amount: 14999 },
      preview_text: "INV-2291 | Rs 14,999",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "customer_communication",
      source_name: "Support Desk",
      title: "Customer Communication - Not Found",
      summary_text: "No support ticket found. Customer filed dispute directly with bank.",
      raw_content_json: { error: "No support ticket found" },
      preview_text: "No support record",
      status: "missing",
      confidence: 0.0,
    },
    {
      case_id: caseId,
      evidence_type: "merchant_policy",
      source_name: "Merchant Policy DB",
      title: "Gadget Lane Dispute Policy",
      summary_text: "RTO disputes should move toward acceptance only after approver confirmation. Initiate refund per 7-day RTO SLA.",
      raw_content_json: { policy: "Accept RTO disputes only after approver confirmation", rto_sla_days: 7 },
      preview_text: "Approver-confirmed acceptance | 7-day SLA",
      status: "found",
      confidence: 1.0,
    },
  ];
}

export function getWeakEvidence(caseId: string): CreateEvidenceItemParams[] {
  return [
    {
      case_id: caseId,
      evidence_type: "payment_record",
      source_name: "Razorpay",
      title: "Payment pay_jkl012 - Captured",
      summary_text: "UPI payment of Rs 899 captured on 2026-03-18.",
      raw_content_json: { payment_id: "pay_jkl012", amount: 899, status: "captured", method: "upi" },
      preview_text: "pay_jkl012 | Rs 899 | captured | UPI",
      status: "found",
      confidence: 1.0,
    },
    {
      case_id: caseId,
      evidence_type: "order_details",
      source_name: "Shopify",
      title: "Order ORD-8801 - Unfulfilled",
      summary_text: "Order ORD-8801: Indoor Plant Combo Set. Status: UNFULFILLED. No AWB assigned.",
      raw_content_json: { order_id: "ORD-8801", fulfillment_status: "unfulfilled", awb: null },
      preview_text: "ORD-8801 | UNFULFILLED | No AWB",
      status: "partial",
      confidence: 0.5,
    },
    {
      case_id: caseId,
      evidence_type: "awb_tracking",
      source_name: "Shiprocket",
      title: "AWB Tracking - NOT FOUND",
      summary_text: "No AWB found for order ORD-8801. Cannot fetch tracking data.",
      raw_content_json: { error: "No AWB found", order_id: "ORD-8801" },
      preview_text: "No AWB | Cannot track",
      status: "missing",
      confidence: 0.0,
    },
    {
      case_id: caseId,
      evidence_type: "logistics_status",
      source_name: "Shiprocket",
      title: "Logistics Status - UNKNOWN",
      summary_text: "Cannot determine logistics status without AWB.",
      raw_content_json: { status: "unknown", reason: "No AWB" },
      preview_text: "Status UNKNOWN | No AWB",
      status: "missing",
      confidence: 0.0,
    },
    {
      case_id: caseId,
      evidence_type: "proof_of_delivery",
      source_name: "Shiprocket",
      title: "Proof of Delivery - NOT AVAILABLE",
      summary_text: "No POD. Order not shipped.",
      raw_content_json: { pod_available: false, reason: "Order not shipped" },
      preview_text: "POD: NOT AVAILABLE",
      status: "missing",
      confidence: 0.0,
    },
    {
      case_id: caseId,
      evidence_type: "invoice",
      source_name: "Merchant ERP",
      title: "Tax Invoice - NOT FOUND",
      summary_text: "No invoice found for unfulfilled order ORD-8801.",
      raw_content_json: { error: "Invoice not found", order_id: "ORD-8801" },
      preview_text: "Invoice NOT FOUND",
      status: "missing",
      confidence: 0.0,
    },
    {
      case_id: caseId,
      evidence_type: "customer_communication",
      source_name: "Support Desk",
      title: "Customer Communication - NOT FOUND",
      summary_text: "No support ticket on record. Customer has not engaged via tracked channels.",
      raw_content_json: { error: "No support ticket found" },
      preview_text: "No communication record",
      status: "missing",
      confidence: 0.0,
    },
    {
      case_id: caseId,
      evidence_type: "merchant_policy",
      source_name: "Merchant Policy DB",
      title: "Fresh Nest Dispute Policy - NOT FOUND",
      summary_text: "No formal dispute policy configured for Fresh Nest.",
      raw_content_json: { error: "No policy configured" },
      preview_text: "No policy found",
      status: "missing",
      confidence: 0.0,
    },
  ];
}

